config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'standup', :to => 'standup#index'
match 'standup/table', :to => 'standup#table', :via => [:get, :post]

post 'standup/set_status', :to => 'standup#set_status'
post 'standup/set_assignee', :to => 'standup#set_assignee'
post 'standup/set_done_ratio', :to => 'standup#set_done_ratio'
post 'standup/new_issue', :to => 'standup#new_issue'
post 'standup/drag_and_drop_date', :to => 'standup#drag_and_drop_date'

match 'standup/context_menu', :to => 'standup#context_menu', :as => 'standup_context_menu', :via => [:get, :post]

app/controllers/standup_controller.rb
class StandupController < ApplicationController

	def index
		@can_add = User.current.allowed_to?(:add_issues, @project)
		@can_edit = User.current.allowed_to?(:edit_issues, @project)
		__prep_table
		nil
	end

	class Issue_wrapper
		@vac_trackers = []
		for i in Tracker.where("name IN ('VAC')") do
			@vac_trackers.push(i.id)
		end
		@new_states = []
		for i in IssueStatus.where("name IN ('New', 'Pending')") do
			@new_states.push(i.id)
		end
		@closed_states = []
		for i in IssueStatus.where("is_closed = true") do
			@closed_states.push(i.id)
		end
		@pending_states = []
		for i in IssueStatus.where("name IN ('Pending', 'Feedback')") do
			@pending_states.push(i.id)
		end

		def initialize(db_entry)
			@db_entry = db_entry

			@end_date = due_date
			if is_closed then
				c = closed_date
				if not @end_date or c < @end_date then
					s = start_date
					if s and s > c then
						@end_date = s
					else
						@end_date = c
					end
				end
			end
		end

		def format_date(date, format, default)
			if date then
				return date.strftime(format)
			else
				return default
			end
		end

		def start_date
			@db_entry.start_date
		end
		def start_date_format(format, default)
			format_date(start_date, format, default)
		end

		def due_date
			@db_entry.due_date
		end
		def due_date_format(format, default)
			format_date(due_date, format, default)
		end

		def closed_date
			@db_entry.closed_on.to_date
		end
		def closed_date_format(format, default)
			format_date(closed_date, format, default)
		end

		def end_date
			@end_date
		end

		def status
			@db_entry.status
		end
		def tracker
			@db_entry.tracker
		end
		def project
			@db_entry.project
		end
		def subject
			@db_entry.subject
		end
		def id
			@db_entry.id
		end
		def done_ratio
			@db_entry.done_ratio
		end
		def category
			@db_entry.category
		end

		def self.pending_states
			@pending_states
		end
		def is_pending
			return Issue_wrapper.pending_states.include? @db_entry.status_id
		end

		def self.closed_states
			@closed_states
		end
		def is_closed
			return Issue_wrapper.closed_states.include? @db_entry.status_id
		end

		def intersect_with_range(b2, e2)
			b1 = start_date
			e1 = end_date
			return (
				(not b1 or not e2 or b1 <= e2) and
				(not b2 or not e1 or b2 <= e1)
			)
		end

		def intersect_with_issue(i)
			return intersect_with_range(i.start_date, i.end_date)
		end

		def intersect_with_group(g)
			for i in g do
				if intersect_with_issue(i) then
					return true
				end
			end
			return false
		end

		def style
			proj_id = @db_entry.project_id
			cat_id = @db_entry.category_id

			proj_styles = StandupAppSpecificHelper.__proj_styles

			if proj_styles.key? proj_id then
				proj = proj_styles[proj_id]
			else
				identifier = Project.find(proj_id).identifier
				if proj_styles.key? identifier then
					proj = proj_styles[identifier]
					proj_styles[proj_id] = proj
				else
					proj = proj_styles[""]
				end
			end

			if cat_id == nil then
				cat_id = ""
			end

			if proj.key? cat_id then
				cat = proj[cat_id]
			else
				name = IssueCategory.find(cat_id).name
				if proj.key? name then
					cat = proj[name]
					proj[cat_id] = cat
				else
					cat = proj[""]
				end
			end

			return cat
		end

	end

	include StandupAppSpecificHelper

	class Empty_filter
		def initialize
			nil
		end
		def match?(str)
			true
		end
	end

	class Word_filter
		def initialize(w)
			@w = w.downcase
			nil
		end
		def match?(str)
			str.downcase.include? @w
		end
	end

	def __prep_table

		# Prepare @proj_ids and @user_ids lists
		__app_prep_table

		@users = User.order(:lastname, :firstname, :id).find(@user_ids)

		begin
			@first_day = Date.strptime(params[:table_start_date], "%Y-%m-%d")
		rescue
			@first_day = Date.today
		end

		begin
			@table_filter = Word_filter.new params[:table_filter]
		rescue
			@table_filter = Empty_filter.new
		end

		@last_day = @first_day + 7
		distant_future = @first_day + 14

		@issues = Issue.where(
			"project_id IN (?) and " +
			"assigned_to_id IN (?) and " +
			"status_id NOT IN (?)",
			@proj_ids,
			@user_ids,
			Issue_wrapper.closed_states
		) + Issue.where(
			"project_id IN (?) and " +
			"assigned_to_id IN (?) and " +
			"status_id IN (?) and " +
			"((start_date is null) or (start_date <= '#{@last_day.strftime("%Y%m%d")}')) and " +
			"((closed_on is null) or ('#{@first_day.strftime("%Y%m%d")}' <= closed_on))",
			@proj_ids,
			@user_ids,
			Issue_wrapper.closed_states
		)
		@issues_by_user = {}
		for i in @users do
			@issues_by_user[i.id] = []
		end
		for i in @issues do
			@issues_by_user[i.assigned_to_id].push(Issue_wrapper.new i)
		end

		@show_user = {}

		for user in @users do
			tasks = @issues_by_user[user.id].sort_by do | u |
				[
					u.tracker.name,
					u.project.name,
					u.subject,
					u.id
				]
			end

			show_user = ( (@table_filter.match? user.firstname) or (@table_filter.match? user.lastname) )
			for task in tasks do
				if not show_user and (@table_filter.match? task.subject) then
					show_user = true
				end
			end
			@show_user[user.id] = show_user
			if not show_user then
				next
			end

			past = []
			present = []
			future = []

			@issues_by_user[user.id] = {
				"past" => past,
				"present" => present,
				"future" => future,
			}
			for task in tasks do
				end_date = task.end_date
				if end_date and end_date < @first_day then
					past.push(task)
					next
				elsif task.start_date and task.start_date > @last_day then
					future.push(task)
					next
				end

				merged = false
				for g in present do
					if not task.intersect_with_group(g) then
						g.push(task)
						merged = true
						break
					end
				end

				if not merged then
					present.push([task])
				end
			end
		end
		nil
	end

	def table
		__prep_table
		render :layout => false
		nil
	end

	def set_status
		@issues = Issue.where(:id => params[:issue_id])
		@issue = @issues.first

		@project = Project.find(@issue.project_id)
		@can_edit = User.current.allowed_to?(:edit_issues, @project)
		if @can_edit then
			journal = @issue.init_journal(User.current, "Changed by 'standup' plugin.")
			@issue.safe_attributes = {"status_id" => params[:status]}
			ok = @issue.save
		end
	rescue
	ensure
		__prep_table
		render :action => "table", :layout => false
		nil
	end

	def set_assignee
		@issues = Issue.where(:id => params[:issue_id])
		@issue = @issues.first

		@project = Project.find(@issue.project_id)
		@can_edit = User.current.allowed_to?(:edit_issues, @project)
		assignee = params[:assignee]
		assignable = true # TODO: project.assignable_users.include? assignee
		if @can_edit and assignable then
			journal = @issue.init_journal(User.current, "Changed by 'standup' plugin.")
			@issue.safe_attributes = {"assigned_to_id" => assignee}
			ok = @issue.save
		end
	rescue
	ensure
		__prep_table
		render :action => "table", :layout => false
		nil
	end

	def set_done_ratio
		@issues = Issue.where(:id => params[:issue_id])
		@issue = @issues.first

		@project = Project.find(@issue.project_id)
		@can_edit = User.current.allowed_to?(:edit_issues, @project)
		if @can_edit then
			journal = @issue.init_journal(User.current, "Changed by 'standup' plugin.")
			@issue.safe_attributes = {"done_ratio" => params[:done_ratio]}
			ok = @issue.save
		end
	rescue
	ensure
		__prep_table
		render :action => "table", :layout => false
		nil
	end

	def drag_and_drop_date
		@issues = Issue.where(:id => params[:issue_id])
		@issue = @issues.first

		@project = Project.find(@issue.project_id)
		@can_edit = User.current.allowed_to?(:edit_issues, @project)
		if @can_edit then
			date = Date.strptime(params[:date], "%Y-%m-%d")
			is_start = params[:is_start] != ""
			is_end = params[:is_end] != ""

			old_start_date = @issue.start_date
			old_due_date = @issue.due_date

			start_date = old_start_date
			due_date = old_due_date

			if is_start && is_end then
				if start_date && date < start_date then
					start_date = date
				end
				if due_date && date > due_date then
					due_date = date
				end
			elsif is_start then
				start_date = date
				if due_date && due_date < date then
					due_date = date
				end
			elsif is_end then
				due_date = date
				if start_date && start_date > date
					start_date = date
				end
			end

			if start_date != old_start_date || due_date != old_due_date then
				journal = @issue.init_journal(User.current, "Changed by 'standup' plugin.")
				@issue.safe_attributes = {
					"start_date" => start_date,
					"due_date" => due_date,
				}
				ok = @issue.save
			end

		end
	rescue
	ensure
		__prep_table
		render :action => "table", :layout => false
		nil
	end

	def new_issue
		@project = Project.find(params[:project_id])
		@can_add = User.current.allowed_to?(:add_issues, @project)
		assignee = params[:assignee]
		assignable = true # TODO: project.assignable_users.include? assignee
		if @can_add and assignable then
			@issue = Issue.create :project => @project,
				:author => User.current,
				:assigned_to_id => assignee,
				:tracker_id => params[:tracker_id],
				:category_id => params[:category_id],
				:parent_issue_id => params[:parent_id],
				:start_date => Date.today,
				:due_date => Date.today,
				:subject => params[:subject]
			#journal = @issue.init_journal(User.current, "Created by 'standup' plugin.")
		end
	rescue
	ensure
		__prep_table
		render :action => "table", :layout => false
		nil
	end

	def context_menu
		issue_id = params[:context_menu_issue_id]
		@issues = Issue.where(:id => issue_id)

		if ! @issues.all?(&:visible?) then
			@issues = []
		end

		render :layout => false
		nil
	rescue ActiveRecord::RecordNotFound
		render_404
		nil
	end
end

app/helpers/standup_helper.rb
module StandupHelper
	include ContextMenusHelper

	def render_box(user, issue, date, weekend)
		if date then
			start_date = issue.start_date
			end_date = issue.end_date
			if (
				(start_date and start_date > date) or
				(end_date and end_date < date)
			) then
				return ""
			end
		end
		
		issue_start = (!date or date == start_date)
		issue_end = (!date or date == end_date)

		pending = (issue.is_pending or weekend)
		unfinished = issue.done_ratio < 100
		
		common_style =
			"box-sizing: border-box; width:100%; " +
			"border-width:0.1em; border-style:solid; " +
			"padding:0.2em; line-height:1em; white-space:nowrap; " +
			"overflow:hidden; text-overflow:ellipsis; "

		extra_style =
			(issue_start ? "border-left-width:0.5em; " : "") +
			(issue_end ? "border-right-width:0.5em; ": "") +
			(pending ? "opacity:0.25; " : "")

		orig_style = common_style + extra_style + issue.style

		return (
"<div
	style='padding:0.0625em'
	class='draggable'

	user_id='#{user.id}'
	issue_id='#{issue.id}'
	date='#{date ? date.strftime("%Y-%m-%d") : ""}'
	is_start='#{issue_start ? "1" : ""}'
	is_end='#{issue_end ? "1" : ""}'
>
	<div
		name='issue#{issue.id}'
		class='issue_div'

		issue_id='#{issue.id}'

		orig_style='#{orig_style}'
		style='#{orig_style}'

		title='
			<b>#{ issue.tracker } ##{ issue.id }:</b> #{ CGI.escapeHTML(issue.subject) }<br>
			<br>
			<b>Status:</b> #{ issue.status }<br>
			<b>Done:</b> #{ issue.done_ratio }%<br>
			<br>
			<b>Project:</b> #{ CGI.escapeHTML(issue.project.name) }<br>
			<b>Category:</b> #{ issue.category }<br>
			<b>Start date:</b> #{ issue.start_date_format('%a %Y-%m-%d', 'unknown') }<br>
			<b>Due date:</b> #{ issue.due_date_format('%a %Y-%m-%d', 'unknown') }<br>
			#{ issue.is_closed ? "<b>Closed date:</b> #{ issue.closed_date_format('%a %Y-%m-%d', 'unknown') }<br>" : "" }'
	>
		".html_safe + issue.subject + "
	</div>
</div>".html_safe)

	end
end

app/views/standup/context_menu.html.erb
<ul>

<%	for issue in @issues do
		project = issue.project
		can_edit = User.current.allowed_to?(:edit_issues, project)
		assignables = issue.assignable_users
		allowed_statuses = issue.new_statuses_allowed_to
		safe_attributes = issue.safe_attribute_names
%>

<%		if @issues.length > 1 then %>
		<li class="folder">
			<a href="#" class="submenu">
				<%= issue.start_date.strftime('%m/%d') %>
				-
				<%= issue.due_date.strftime('%m/%d') %>:
				<%= issue.subject %>
			</a>
			<ul>
<%		end %>

		<li>
			<%= context_menu_link "View", issue_path(issue) %>
		</li>

		<li>
			<%= context_menu_link l(:button_edit),
				edit_issue_path(issue),
				:class => 'icon-edit',
				:disabled => ! can_edit
			%>
		</li>

<%		if @issues.length <= 1 then %>

		<% if allowed_statuses.present? then %>
		<li class="folder">
			<a href="#" class="submenu"><%= l(:field_status) %></a>
			<ul>
				<% allowed_statuses.each do |s| %>
				<li>
					<%= context_menu_link h(s.name), "#",
						:onclick => "__my_process_click(\"set_status\", {issue_id:\"#{issue.id}\", status:\"#{s.id}\"}); return false",
						:selected => s == issue.status,
						:disabled => ! can_edit
					%>
				</li>
				<% end %>
			</ul>
		</li>
		<% end %>

		<% if safe_attributes.include?('assigned_to_id') && assignables.present? then %>
		<li class="folder">
			<a href="#" class="submenu"><%= l(:field_assigned_to) %></a>
			<ul>
				<% if assignables.include?(User.current) then %>
				<li>
					<%= context_menu_link "<< #{l(:label_me)} >>", "#",
						:onclick => "__my_process_click(\"set_assignee\", {issue_id:\"#{issue.id}\", assignee:\"#{User.current.id}\"}); return false",
						:selected => User.current == issue.assigned_to,
						:disabled => ! can_edit
					%>
				</li>
				<% end %>

				<% assignables.each do |u| %>
				<li>
					<%= context_menu_link h(u.name), "#",
						:onclick => "__my_process_click(\"set_assignee\", {issue_id:\"#{issue.id}\", assignee:\"#{u.id}\"}); return false",
						:selected => u == issue.assigned_to,
						:disabled => ! can_edit
					%>
				</li>
				<% end %>
			</ul>
		</li>
		<% end %>

		<% if safe_attributes.include?('done_ratio') && Issue.use_field_for_done_ratio? then %>
		<li class="folder">
			<a href="#" class="submenu"><%= l(:field_done_ratio) %></a>
			<ul>
			<% (0..10).map{|x|x*10}.each do |p| -%>
				<li>
				<%= context_menu_link "#{p}%", "#",
					:onclick => "__my_process_click(\"set_done_ratio\", {issue_id:\"#{issue.id}\", done_ratio:\"#{p}\"}); return false",
					:selected => (issue && p == issue.done_ratio),
					:disabled => ! (can_edit && issue.leaf?)
				%>
				</li>
			<% end %>
			</ul>
		</li>
		<% end %>

<%		end %>

<%		if @issues.length > 1 then %>
			</ul>
		</li>
<%		end %>

<%	end %>
		
<%	if @issues.length > 0 then %>

		<li> <hr> </li>

<%	end %>

		<li class="folder">
			<a href="#" class="submenu">New</a>
			<ul>
				<li><%=
					context_menu_link "AX",
						request.base_url +
						#"/redmine" +
						"/projects/ax/issues/new?" +
						"issue[tracker_id]="+"6"+"&" +
						"issue[assigned_to_id]="+params[:context_menu_user_id]+"&" +
						"issue[start_date]="+params[:context_menu_date]+"&" +
						"issue[due_date]="+params[:context_menu_date]+"&" +
						"issue[subject]="+"TODO"
				%></li>
				<li><%=
					context_menu_link "X2",
						request.base_url +
						#"/redmine" +
						"/projects/x2/issues/new?" +
						"issue[tracker_id]="+"6"+"&" +
						"issue[assigned_to_id]="+params[:context_menu_user_id]+"&" +
						"issue[start_date]="+params[:context_menu_date]+"&" +
						"issue[due_date]="+params[:context_menu_date]+"&" +
						"issue[subject]="+"TODO"
				%></li>
				<li><%=
					context_menu_link "Refresh",
						request.base_url +
						#"/redmine" +
						"/projects/refresh/issues/new?" +
						"issue[tracker_id]="+"6"+"&" +
						"issue[assigned_to_id]="+params[:context_menu_user_id]+"&" +
						"issue[start_date]="+params[:context_menu_date]+"&" +
						"issue[due_date]="+params[:context_menu_date]+"&" +
						"issue[subject]="+"TODO"
				%></li>
				<li><%=
					context_menu_link "New SW Master",
						request.base_url +
						#"/redmine" +
						"/projects/new-software-master/issues/new?" +
						"issue[tracker_id]="+"6"+"&" +
						"issue[assigned_to_id]="+params[:context_menu_user_id]+"&" +
						"issue[start_date]="+params[:context_menu_date]+"&" +
						"issue[due_date]="+params[:context_menu_date]+"&" +
						"issue[subject]="+"TODO"
				%></li>

				<li> <hr> </li>

				<li><%=
					context_menu_link "CZ Private",
						request.base_url +
						#"/redmine" +
						"/projects/cz-private/issues/new?" +
						"issue[tracker_id]="+"6"+"&" +
						"issue[assigned_to_id]="+params[:context_menu_user_id]+"&" +
						"issue[start_date]="+params[:context_menu_date]+"&" +
						"issue[due_date]="+params[:context_menu_date]+"&" +
						"issue[subject]="+"TODO"
				%></li>

				<li><%=
					context_menu_link "VAC",
						request.base_url +
						#"/redmine" +
						"/projects/tasktracker/issues/new?" +
						"issue[tracker_id]="+"10"+"&" +
						"issue[assigned_to_id]="+params[:context_menu_user_id]+"&" +
						"issue[start_date]="+params[:context_menu_date]+"&" +
						"issue[due_date]="+params[:context_menu_date]+"&" +
						"issue[subject]="+"VAC"
				%></li>
			</ul>
		</li>

		<li>
			<%= context_menu_link "Reload Table", "#",
				:onclick => "__my_process_click(\"table\", {}); return false",
				:class => 'icon-reload'
			%>
		</li>

</ul>

app/views/standup/index.html.erb
<h2>standup</h2>

<% table_start_date = params[:table_start_date] %>
<% if not table_start_date then table_start_date = 'today' end %>

<% table_filter = params[:table_filter] %>

<form>
	<div class="box">
		<table>
		<tr>
			<td>
				<label for='table_start_date'>First day to show:</label>
			</td>
			<td>
				<input id="table_start_date" name="table_start_date" autocomplete="off" size="10" type="text" value="<%= table_start_date %>"/>
				<%= calendar_for('table_start_date') %>
			</td>
		</tr>
		<tr>
			<td>
				<label for='table_filter'>Filter:</label>
			</td>
			<td>
				<input id="table_filter" name="table_filter" autocomplete="off" size="10" type="text" value="<%= table_filter %>"/>
			</td>
		</tr>
		<tr>
			<td>
			</td>
			<td>
				<input type="submit" value="Apply">
			</td>
		</tr>
		</table>
	</div>
</form>

<form accept-charset="UTF-8" method="post">
	<input name="context_menu_user_id" type="hidden" value=""/>
	<input name="context_menu_issue_id" type="hidden" value=""/>
	<input name="context_menu_date" type="hidden" value=""/>

	<div id='div_with_table'>

	</div>
</form>

<br>
<br>

<script type="text/javascript">
//<![CDATA[

	function __issue_in(event) {
		var issue_id = $(event.target).attr("issue_id")
		$("[name=issue"+issue_id+"]").each(function() {
			var e = $(this)
			e.attr("style", e.attr("orig_style") + "; color:black; background-color:#ff9080; border-color:#8f1000")
		})
	}
	function __issue_out(event) {
		var issue_id = $(event.target).attr("issue_id")
		$("[name=issue"+issue_id+"]").each(function() {
			var e = $(this)
			e.attr("style", e.attr("orig_style"))
		})
	}

	function __right_click(event) {
		var t = $(event.target)
		var d = t.closest(".draggable")
		if (d.length) {
			t = d
		} else {
			t = t.closest("td[user_id]")
			if (!t.length) { return }
		}

		$("input[name=context_menu_user_id]" ).val( t.attr("user_id") )
		$("input[name=context_menu_issue_id]").val( t.attr("issue_id") )
		$("input[name=context_menu_date]"    ).val( t.attr("date") )
	}

	function __helper() {
		var t = $(this)
		var q = t.clone()
		q.css("width", t.width())
		return q
	}
	function __allow_drop(task) {
		var cell = $(this)
		return (cell.attr("user_id") != task.attr("user_id")) ||
		       ( cell.attr("date") != "" &&
		         cell.attr("date") != task.attr("date") &&
		         ( (task.attr("is_start") != "") ||
		           (task.attr("is_end") != "")
		         )
		       )
	}
	function __drop(e, ui) {
		var task = $(ui.draggable)
		var cell = $(this)

		if (cell.attr("user_id") != task.attr("user_id")) {
			__my_process_click("set_assignee", {
				issue_id: task.attr("issue_id"),
				assignee: cell.attr("user_id"),
			})
		} else {
			__my_process_click("drag_and_drop_date", {
				issue_id: task.attr("issue_id"),
				is_start: task.attr("is_start"),
				is_end: task.attr("is_end"),
				date: cell.attr("date")
			})
		}

		$(ui.helper).remove()
	}
	function __after_reload() {
		$(".draggable").draggable({
			helper: __helper,
			revert: "invalid",
			//containment: "window",
			//appendTo: 'body',
		});
		$(".droppable").droppable({drop: __drop, accept:__allow_drop})
		$(".issue_div").hover(__issue_in, __issue_out)
	}
	function __my_process_click(page, attrs) {
		attrs.table_start_date = "<%= table_start_date %>"
		attrs.table_filter = "<%= table_filter %>"
		$("#div_with_table").load("<%= standup_path %>/"+page, attrs, __after_reload);
	}
	function __init() {
		var attrs = {}
		attrs.table_start_date = "<%= table_start_date %>"
		attrs.table_filter = "<%= table_filter %>"
		$("#div_with_table").load("<%= standup_path %>/table", attrs, __after_reload);
		$("#table_start_date").datepicker();
	}

	$(document).contextmenu(__right_click);
	$(document).tooltip({
		items: "[title]",
		show: {
			delay: 600,
		},
		content: function() {
			var element = $( this );
			return element.attr( "title" );
		}
	})

	$(__init)
//]]>
</script>

<%= context_menu standup_context_menu_path %>